# Generated by Django 3.0.7 on 2020-06-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beach_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_name', models.CharField(max_length=255, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('position', models.TextField(max_length=255)),
                ('beach_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='zon_cam', to='api.Beach')),
            ],
        ),
    ]
