# Generated by Django 3.0.7 on 2020-06-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonecamera',
            old_name='beach_id',
            new_name='beach',
        ),
        migrations.AddField(
            model_name='beach',
            name='position',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zonecamera',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zonecamera',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zonecamera',
            name='light_state',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CountLogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='count_data', to='api.ZoneCamera')),
            ],
        ),
    ]
