# Generated by Django 3.0.7 on 2020-06-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200628_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonecamera',
            name='position',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
