# Generated by Django 3.0.7 on 2020-07-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200628_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_id', models.CharField(max_length=255, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('usr', models.CharField(max_length=255, null=True)),
                ('pwd', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jetson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jetson_id', models.CharField(max_length=255, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('usr', models.CharField(max_length=255, null=True)),
                ('pwd', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='beach',
            old_name='position',
            new_name='location_coord',
        ),
        migrations.AddField(
            model_name='beach',
            name='location_degree',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beach',
            name='traffic_level',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=255, unique=True)),
                ('location_coord', models.TextField(max_length=255, null=True)),
                ('location_degree', models.TextField(max_length=255, null=True)),
                ('count', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('traffic_level', models.TextField(max_length=255, null=True)),
                ('light_state', models.IntegerField(null=True)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='zon_cam', to='api.Beach')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=255, unique=True)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='station', to='api.Beach')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_id', models.CharField(max_length=255, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('usr', models.CharField(max_length=255, null=True)),
                ('pwd', models.CharField(max_length=255, null=True)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='router', to='api.Beach')),
            ],
        ),
        migrations.AlterField(
            model_name='countlogdata',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='count_data', to='api.Zone'),
        ),
        migrations.DeleteModel(
            name='ZoneCamera',
        ),
    ]
