# Generated by Django 3.0.7 on 2020-07-01 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200701_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_id', models.CharField(max_length=255, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('usr', models.CharField(max_length=255, null=True)),
                ('pwd', models.CharField(max_length=255, null=True)),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camera', to='api.Beach')),
            ],
        ),
        migrations.DeleteModel(
            name='Cam',
        ),
        migrations.AddField(
            model_name='jetson',
            name='beach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jetson', to='api.Beach'),
            preserve_default=False,
        ),
    ]
